export const player = {
  spellsList: [
    {
      name: 'renew',
      type: 'hot',
      targets: 1,
      hotsFreq: 1,
      hotsRep: 10,
      healAmount: 1,
      cooldown: 0,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
    {
      name: 'holy',
      type: 'heal',
      targets: 1,
      hotsFreq: 0,
      hotsRep: 1,
      healAmount: 0,
      cooldown: 0,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
    {
      name: 'shield',
      type: 'heal',
      targets: 1,
      hotsFreq: 0,
      hotsRep: 1,
      healAmount: 5,
      cooldown: 5,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
    {
      name: 'circle',
      type: 'hot',
      targets: 5,
      hotsFreq: 0,
      hotsRep: 1,
      healAmount: 2,
      cooldown: 3,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
    {
      name: 'lastStand',
      type: 'heal',
      targets: 1,
      hotsFreq: 0,
      hotsRep: 1,
      healAmount: 50,
      cooldown: 40,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
    {
      name: 'hotRenew',
      type: 'hot',
      targets: 11,
      hotsFreq: 0.5,
      hotsRep: 6,
      healAmount: 2,
      cooldown: 40,
      currentWidth: 100,
      manaCost: 5,
      timer: 0,
    },
  ],
  mana: {
    currentWidth: 100,
    regen: 0.1,
    regenFreq: 1,
  },
};
